### ISSUE TITLE
ISSUES: Values on the Wallets page don't match the value of "Today's Price" if you calculate 

### ISSUE THREAD

**Issue by CriLoma** [unicef/juniper-portfolio#383]
If I'm on the Wallets page, the "Current Balance" that is showing up doesn't match the value I would get if I was taking the "Today's Price" and multiplying it by the wallet balances. 

For example, in the screenshot, the "today's value" for ether is 1,539.44 and if I multiply that by 1,041.7279 then I get 1,603,677.60.. but the site shows me $1,603,676.76.

Please verify all prices on this page are being calculated properly.

![image](https://user-images.githubusercontent.com/49003323/110017129-db1dea00-7cf3-11eb-9b40-5413481990c7.png)

**Comment by tenthirtyone** [comment]
Ah, so it looks like this is because 'under the hood' the app rounds USD to 2 decimals and Crypto to 4 and the bug is that the crypto is rounded to 4 places on the UI, not when it is set by the app. So the balance amount is using 1041.72787 'under the hood' and the same for the rate. The cause of the discrepancy is the errant decimals.

I can change this on the server to round eth/btc amounts to 4 places. The front end will still handle rounding for the prices because our daily price is part of an array of all the price history but uses the most recent date (This was for defensive programming so if a day isn't stored in the db the app will not crash or use 0 or another arbitrary number).

**Comment by CriLoma** [comment]
@mehranhydary ^
